# Generated by Django 5.1.6 on 2025-02-11 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_product_image_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='app_cart',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='app_customer',
        ),
        migrations.AlterModelTable(
            name='orderplaced',
            table='app_orderplaced',
        ),
    ]
